name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  ci:
    name: CI Script with Lerna
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run: npx lerna bootstrap
      - name: CI Tasks
        run: npx lerna run ci
