name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  ci:
    name: CI Script with Lerna
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run: npm ci
      - name: Prepare npm auth
        run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > ./.npmrc
      - name: Prepare npm auth for leaf project
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ./eslint-config-jsdoc-linter/.npmrc
      - name: Update index
        run: |
          git update-index --assume-unchanged .npmrc
          git update-index --assume-unchanged ./eslint-config-jest-linter/.npmrc
          git update-index --assume-unchanged ./eslint-config-js-linter/.npmrc
          git update-index --assume-unchanged ./eslint-config-jsdoc-linter/.npmrc
          git update-index --assume-unchanged ./eslint-config-react-linter/.npmrc
      - name: Publish with npm
        run: npm publish --access public
        working-directory: ./eslint-config-jsdoc-linter
