name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        cwd: [javascript, typescript]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/jod
      - run: npm ci
        working-directory: ${{ matrix.cwd }}
      - run: npm run lint
        working-directory: ${{ matrix.cwd }}
